# Generated by Django 5.2.8 on 2025-11-16 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descricao', models.TextField()),
                ('data_evento', models.DateField()),
                ('local', models.CharField(max_length=200)),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='api.campanha')),
            ],
        ),
    ]
