# Generated by Django 5.2.8 on 2025-11-16 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_doacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='doacao',
            name='campanha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doacoes', to='api.campanha'),
        ),
    ]
