# Generated by Django 5.2.8 on 2025-11-16 19:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_instituicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='campanha',
            name='participantes',
            field=models.ManyToManyField(blank=True, related_name='campanhas_participadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
