# Generated by Django 5.2.8 on 2025-11-16 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_campanha_participantes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApoioInstituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_apoio', models.CharField(help_text='Ex: Financeiro, Logístico, Divulgação', max_length=100)),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.campanha')),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.instituicao')),
            ],
            options={
                'unique_together': {('instituicao', 'campanha')},
            },
        ),
        migrations.AddField(
            model_name='campanha',
            name='instituicoes_apoio',
            field=models.ManyToManyField(blank=True, related_name='campanhas_apoiadas', through='api.ApoioInstituicao', to='api.instituicao'),
        ),
    ]
