# Generated by Django 5.2.8 on 2025-11-16 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_apoioinstituicao_campanha_instituicoes_apoio'),
    ]

    operations = [
        migrations.AddField(
            model_name='campanha',
            name='imagem_capa',
            field=models.ImageField(blank=True, null=True, upload_to='campanhas/'),
        ),
    ]
