# Generated by Django 5.2.8 on 2025-11-20 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_campanha_imagem_capa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apoioinstituicao',
            name='tipo_apoio',
            field=models.CharField(help_text='Ex: Financeiro, Logístico', max_length=100),
        ),
    ]
