# Generated by Django 5.2.8 on 2025-11-23 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depoimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('texto', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='depoimentos/')),
                ('cargo', models.CharField(blank=True, help_text='Ex: Estudante, Voluntário', max_length=100)),
            ],
        ),
    ]
